[tool.poetry]
name = "uni-scheduler"
version = "0.1.0"
description = "Extract university chedule from pdf spreadsheet and add to Google Calendar"
authors = ["Tristan Brand <tristanbrand09@gmail.com>"]
readme = "README.md"
packages = [{ include = "uni_scheduler", from = "src" }]

[tool.poetry.dependencies]
python = ">=3.10,<3.14"
pandas = "^2.2.0"
tabula-py = "^2.9.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"
ruff = "^0.6.0"

[tool.poetry.scripts]
pdf-sheet = "pdf_sheet_tool.main:main"

[tool.ruff]
line-length = 100

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
